### ISSUE TITLE
Exception in plugin PyCharm Odoo (4.12)

### ISSUE THREAD

**Issue by ievgensyn** [odoo-ide/pycharm-odoo-old#32]
PyCharm 2020.3.2 (Community Edition)
Build #PC-203.6682.179, built on December 30, 2020
Runtime version: 11.0.9.1+11-b1145.63 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-64-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Non-Bundled Plugins: net.seesharpsoft.intellij.plugins.csv, dev.ngocta.pycharm-odoo, net.firebits.odoo
Current Desktop: X-Cinnamon

java.lang.Throwable: Non-idempotent computation: it returns different results when invoked multiple times or on different threads:
  5 != 3
  which is length of [PyFile:models.py@0, PyFile:models.py@0, PyFile:models.py@0, PyFile:models.py@0, PyImportElement:models@-1000] and [PyFile:models.py@0, PyFile:models.py@0, PyImportElement:models@-1000]

Recomputation gives [Lcom.intellij.psi.ResolveResult;@5ccda985 (class [Lcom.intellij.psi.ResolveResult;) which is equivalent to 'fresh'
Recomputation log:
  Resolving dev.ngocta.pycharm.odoo.python.psi.OdooPyReference@3aed5556 of class dev.ngocta.pycharm.odoo.python.psi.OdooPyReference
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:159)
	at com.intellij.util.IdempotenceChecker.reportFailure(IdempotenceChecker.java:88)
	at com.intellij.util.IdempotenceChecker.checkEquivalence(IdempotenceChecker.java:75)
	at com.intellij.psi.impl.source.resolve.ResolveCache.cache(ResolveCache.java:282)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:210)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:149)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:164)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:157)
	at com.jetbrains.python.psi.impl.references.PyReferenceImpl.multiResolve(PyReferenceImpl.java:95)
	at com.jetbrains.python.psi.impl.references.PyReferenceImpl.resolve(PyReferenceImpl.java:74)
	at dev.ngocta.pycharm.odoo.python.model.OdooLambdaTypeProvider.getReferenceExpressionType(OdooLambdaTypeProvider.java:22)
	at com.jetbrains.python.psi.impl.PyReferenceExpressionImpl.getTypeFromProviders(PyReferenceExpressionImpl.java:386)
	at com.jetbrains.python.psi.impl.PyReferenceExpressionImpl.getType(PyReferenceExpressionImpl.java:219)
	at com.jetbrains.python.psi.types.TypeEvalContext.lambda$getType$0(TypeEvalContext.java:180)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.jetbrains.python.psi.types.TypeEvalContext.getType(TypeEvalContext.java:169)
	at com.jetbrains.python.codeInsight.stdlib.PyNamedTupleTypeProvider$Companion.getFieldTypeForNamedTupleAsTarget(PyNamedTupleTypeProvider.kt:87)
	at com.jetbrains.python.codeInsight.stdlib.PyNamedTupleTypeProvider$Companion.access$getFieldTypeForNamedTupleAsTarget(PyNamedTupleTypeProvider.kt:54)
	at com.jetbrains.python.codeInsight.stdlib.PyNamedTupleTypeProvider.getReferenceExpressionType(PyNamedTupleTypeProvider.kt:31)
	at com.jetbrains.python.psi.impl.PyReferenceExpressionImpl.getTypeFromProviders(PyReferenceExpressionImpl.java:386)
	at com.jetbrains.python.psi.impl.PyReferenceExpressionImpl.getType(PyReferenceExpressionImpl.java:219)
	at com.jetbrains.python.psi.types.TypeEvalContext.lambda$getType$0(TypeEvalContext.java:180)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.jetbrains.python.psi.types.TypeEvalContext.getType(TypeEvalContext.java:169)
	at com.jetbrains.python.psi.impl.PyClassImpl.fillSuperClassesSwitchingToAst(PyClassImpl.java:1356)
	at com.jetbrains.python.psi.impl.PyClassImpl.doGetSuperClassTypes(PyClassImpl.java:1340)
	at com.jetbrains.python.psi.PyUtil.getNullableParameterizedCachedValue(PyUtil.java:668)
	at com.jetbrains.python.psi.PyUtil.getParameterizedCachedValue(PyUtil.java:646)
	at com.jetbrains.python.psi.impl.PyClassImpl.getSuperClassTypes(PyClassImpl.java:1328)
	at com.jetbrains.python.psi.impl.PyClassImpl.getSuperClasses(PyClassImpl.java:305)
	at dev.ngocta.pycharm.odoo.python.model.OdooModelClass.lambda$getExplicitAncestorClasses$1(OdooModelClass.java:104)
	at com.jetbrains.python.psi.PyUtil.getNullableParameterizedCachedValue(PyUtil.java:668)
	at com.jetbrains.python.psi.PyUtil.getParameterizedCachedValue(PyUtil.java:646)
	at dev.ngocta.pycharm.odoo.python.model.OdooModelClass.getExplicitAncestorClasses(OdooModelClass.java:96)
	at dev.ngocta.pycharm.odoo.python.model.OdooModelClass.getAncestorClasses(OdooModelClass.java:77)
	at dev.ngocta.pycharm.odoo.python.model.OdooModelClass.visitMembers(OdooModelClass.java:545)
	at dev.ngocta.pycharm.odoo.python.model.OdooModelClass.lambda$findField$12(OdooModelClass.java:573)
	at com.jetbrains.python.psi.PyUtil.getNullableParameterizedCachedValue(PyUtil.java:668)
	at dev.ngocta.pycharm.odoo.python.model.OdooModelClass.findField(OdooModelClass.java:571)
	at dev.ngocta.pycharm.odoo.python.model.OdooModelClass.lambda$findFieldsInPath$13(OdooModelClass.java:611)
	at com.jetbrains.python.psi.PyUtil.getNullableParameterizedCachedValue(PyUtil.java:668)
	at com.jetbrains.python.psi.PyUtil.getParameterizedCachedValue(PyUtil.java:646)
	at dev.ngocta.pycharm.odoo.python.model.OdooModelClass.findFieldsInPath(OdooModelClass.java:605)
	at dev.ngocta.pycharm.odoo.python.model.OdooModelClass.findFieldByPath(OdooModelClass.java:595)
	at dev.ngocta.pycharm.odoo.python.model.OdooModelClass.findFieldByPath(OdooModelClass.java:589)
	at dev.ngocta.pycharm.odoo.python.model.OdooFieldInfo.getRelatedField(OdooFieldInfo.java:87)
	at dev.ngocta.pycharm.odoo.python.model.OdooFieldInfo.getRelatedFieldInfo(OdooFieldInfo.java:92)
	at dev.ngocta.pycharm.odoo.python.model.OdooFieldInfo.doGetComodel(OdooFieldInfo.java:63)
	at dev.ngocta.pycharm.odoo.python.model.OdooFieldInfo.getComodel(OdooFieldInfo.java:53)
	at dev.ngocta.pycharm.odoo.python.model.OdooFieldInfo.getType(OdooFieldInfo.java:192)
	at dev.ngocta.pycharm.odoo.python.model.OdooFieldInfo.getFieldType(OdooFieldInfo.java:228)
	at dev.ngocta.pycharm.odoo.python.model.OdooModelUtils.guessFieldTypeByName(OdooModelUtils.java:544)
	at dev.ngocta.pycharm.odoo.python.model.OdooFieldTypeProvider.getReferenceExpressionType(OdooFieldTypeProvider.java:45)
	at com.jetbrains.python.psi.impl.PyReferenceExpressionImpl.getTypeFromProviders(PyReferenceExpressionImpl.java:386)
	at com.jetbrains.python.psi.impl.PyReferenceExpressionImpl.getType(PyReferenceExpressionImpl.java:219)
	at com.jetbrains.python.psi.types.TypeEvalContext.lambda$getType$0(TypeEvalContext.java:180)
	at com.intellij.openapi.util.RecursionManager$1.computePreventingRecursion(RecursionManager.java:111)
	at com.intellij.openapi.util.RecursionGuard.doPreventingRecursion(RecursionGuard.java:42)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:68)
	at com.jetbrains.python.psi.types.TypeEvalContext.getType(TypeEvalContext.java:169)
	at com.jetbrains.python.inspections.PyDataclassInspection$Visitor.getInstancePyClass(PyDataclassInspection.kt:267)
	at com.jetbrains.python.inspections.PyDataclassInspection$Visitor.visitPyReferenceExpression(PyDataclassInspection.kt:215)
	at com.jetbrains.python.psi.impl.PyReferenceExpressionImpl.acceptPyVisitor(PyReferenceExpressionImpl.java:88)
	at com.jetbrains.python.psi.impl.PyBaseElementImpl.accept(PyBaseElementImpl.java:69)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:66)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:57)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.doInspectInjectedPsi(LocalInspectionsPass.java:786)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$inspectInjectedPsi$9(LocalInspectionsPass.java:354)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:136)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:92)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:104)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:83)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:183)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:83)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by trinhanhngoc** [comment]
Duplicate #28
